version: 2
jobs:
  build:
    docker:
      - image: node:10.16.3

    working_directory: ~/sample

    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

